//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Trade.MvsWebUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class hesapodemeleri
    {
        public int Id { get; set; }
        public int musteriid { get; set; }
        public int adisyonid { get; set; }
        public Nullable<int> odemeturid { get; set; }
        public Nullable<decimal> aratoplam { get; set; }
        public Nullable<decimal> indirim { get; set; }
        public Nullable<decimal> toplamtutar { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual adisyonlar adisyonlar { get; set; }
        public virtual odemeturleri odemeturleri { get; set; }
    }
}
