//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Trade.MvsWebUI.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class developerEntities : DbContext
    {
        public developerEntities()
            : base("name=developerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adisyonlar> adisyonlar { get; set; }
        public virtual DbSet<hesapodemeleri> hesapodemeleri { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<masalar> masalar { get; set; }
        public virtual DbSet<müsteriler> müsteriler { get; set; }
        public virtual DbSet<odemeturleri> odemeturleri { get; set; }
        public virtual DbSet<paketsiparis> paketsiparis { get; set; }
        public virtual DbSet<personelhareketleri> personelhareketleri { get; set; }
        public virtual DbSet<personeller> personeller { get; set; }
        public virtual DbSet<pesonelgorevleri> pesonelgorevleri { get; set; }
        public virtual DbSet<rezervasyolar> rezervasyolar { get; set; }
        public virtual DbSet<satislar> satislar { get; set; }
        public virtual DbSet<servisturu> servisturu { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
    }
}
