//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Trade.MvsWebUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class pesonelgorevleri
    {
        public int Id { get; set; }
        public string gorev { get; set; }
        public string aciklama { get; set; }
        public bool durum { get; set; }
    }
}
