//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Trade.MvsWebUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class satislar
    {
        public int Id { get; set; }
        public int adisyonid { get; set; }
        public int urunid { get; set; }
        public int masaid { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<bool> durum { get; set; }
    }
}
